name = "Create"
author = "niodtn"
version = "1.1.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b4ae46dc2092b2534c08669f739eb8ee1add7e411ede83affb003dacb5b160e7"

[versions]
fabric = "0.15.11"
minecraft = "1.20.1"
