name = "Create"
author = "niodtn"
version = "1.1.5"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "800387916ab945f79c8513ba1faca2d8602dff3db619e0062e76298f31beee5e"

[versions]
fabric = "0.15.11"
minecraft = "1.20.1"
