name = "Create"
author = "niodtn"
version = "1.3.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "55c94b76b76d300251fa6750d4ced5092a06550efddd794f1a30574307544c10"

[versions]
fabric = "0.15.11"
minecraft = "1.20.1"
