name = "Create"
author = "niodtn"
version = "1.1.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "bae1f5907bc57e758715a4707d739e64ca64972b3e6a605cf48610c079278a27"

[versions]
fabric = "0.15.11"
minecraft = "1.20.1"
