name = "Create"
author = "niodtn"
version = "1.3.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "136df48a6f5da2557a8720483f633ba15fe6496471bcef4177aa6226bc1bacbd"

[versions]
fabric = "0.15.11"
minecraft = "1.20.1"
