name = "Create"
author = "niodtn"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "bd8bbe25e5c871dd1cdec1b44199380322343b06c9367ef86b9043b10bd8987f"

[versions]
fabric = "0.15.11"
minecraft = "1.20.1"
