name = "Create"
author = "niodtn"
version = "1.1.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e6fdcfa38c57f5595653ff070013568f07078daeeeeeecc318815c4eda6dd693"

[versions]
fabric = "0.15.11"
minecraft = "1.20.1"
