name = "Create"
author = "niodtn"
version = "1.4.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "cb6741afc90153c28fd25a8b518aa67048f9938c8decedc8c12113536c112688"

[versions]
fabric = "0.15.11"
minecraft = "1.20.1"
