name = "Create"
author = "niodtn"
version = "0.1.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "34e8ee1d671dfef43f501f7759f81960e26a66e96cd45bc3c32837d76e7286b6"

[versions]
fabric = "0.15.11"
minecraft = "1.20.1"
